// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CharacterContext))]
    partial class CharacterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("backend.Models.CharacterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Game")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                    new CharacterModel
                    {
                        Id = 1,
                        Name = "Sephiroth",
                        Game = "Final Fantasy VII",
                        ImgUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.mariowiki.com%2Fimages%2Fthumb%2Fd%2Fd6%2FSSBU_Sephiroth.png%2F1200px-SSBU_Sephiroth.png&f=1&nofb=1"
                    },
                                new CharacterModel
                                {
                                    Id = 2,
                                    Name = "Cloud",
                                    Game = "FFVII",
                                    ImgUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvignette.wikia.nocookie.net%2Ffinalfantasy%2Fimages%2F6%2F69%2FSSBU_Cloud_Strife_render_002.png%2Frevision%2Flatest%2Fscale-to-width-down%2F2000%3Fcb%3D20180918182717&f=1&nofb=1"
                                },
                                new CharacterModel
                                {
                                    Id = 3,
                                    Name = "Garland",
                                    Game = "FF",
                                    ImgUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvignette.wikia.nocookie.net%2Ffinalfantasy%2Fimages%2F0%2F0e%2FDFF2015_Garland_Render.png%2Frevision%2Flatest%3Fcb%3D20160811183610&f=1&nofb=1"
                                }
                                        );
                });


#pragma warning restore 612, 618
        }
    }
}
